def options():
    return {
        "names_files": {
            "names_CHAR18_Manufacturer_EU": 18,
            "names_CHAR18_Manufacturer_JP": 18,
            "names_CHAR18_Manufacturer_US": 18,
            "names_CHAR18_Common_EU": 18,
            "names_CHAR18_Common_JP": 18,
            "names_CHAR18_Common_US": 18,
            "names_CHAR28_Manufacturer_EU": 28,
            "names_CHAR28_Manufacturer_JP": 28,
            "names_CHAR28_Manufacturer_US": 28,
            "names_CHAR28_Common_EU": 28,
            "names_CHAR28_Common_JP": 28,
            "names_CHAR28_Common_US": 28,
            "names_CHAR54_Manufacturer_EU": 54,
        },
        "csv_separator": ";",
        "csv_quote_char": '|',
        "format_line_separator": "|",
        "formatter_line_names_txt": "                   |                  |         |                         |",
        "straight_line_char": "=",
        "padding_char": " ",
        "straight_line_every": 40,
        "format_line_every": 10,
        "output_names_csv": "names.csv",
        "input_names_csv": "names.csv",
        "cores_column_rightpadding_csv": 30,
        "cores_column_rightpadding_txt": 19,
        "cores_column_name": "Cores",
        "stip_from_reference": "names_CHAR",
        "big_space_before_core": "Arkanoid",
        "big_space_line_quantity": 10,
    }