name: Regenerate Files
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: Regenerate Files
        run: |
          set -euo pipefail
          git config --global user.email "theypsilon@gmail.com"
          git config --global user.name "The CI/CD Bot"
          ./.github/regenerate_files.sh
        env:
          URL_BASE: https://raw.githubusercontent.com/ThreepwoodLeBrush/Names_MiSTer/%s/
          GIT_PUSH: 'true'
